

name: test
run-name: Validation script ${{ github.ref_name }} via ${{ github.event_name }} par ${{ github.actor }}

on:
  pull_request:
    branches:
      - master

jobs:
    test:
        runs-on: alpine-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: run script
              run: bash ./H3Etudiant.sh